### ISSUE TITLE
Replace ASM files with #[naked] functions

### ISSUE THREAD

**Issue by iankronquist** [iankronquist/rustyvisor#35]
Let's go pure rust on this. We're already using inline assembly, let's go all the way.

Remember to add a feature flag to lib.rs.

https://github.com/rust-lang/rust/pull/32410

**Comment by s-mcf** [comment]
We can use the x86-interrupt ABI and avoid writing inline assembly entirely.

Tracking issue: rust-lang/rust#20180
PR with some meager documentation: rust-lang/rust#39832
No RFC exists AFAIK.

**Comment by iankronquist** [comment]
Deprecated in favor of a UEFI runtime service.
