### ISSUE TITLE
So where is documentation how to use it ? 

### ISSUE THREAD

**Issue by denisgolius** [iankronquist/rustyvisor#45]
So where is documentation how to use it ?

**Comment by iankronquist** [comment]
This is a work in progress which doesn't quite work yet :)
If you'd like to try it out, read the README, which will show you how to build and install it. It will crash your computer though and could do nastier things so caveat emptor!
PRs welcome too if you want to fix something!

**Comment by iankronquist** [comment]
Of you try it out, look at the vmcs_fields_integration branch, which is the most complete, although very crashy.
